const VendorData = [
  {
    id: 1,
    name: "Shutterbugs Photography",
    location: "Kolar",
    serviceType: "Photography",
    priceRange: 20000,
    rating: 4,
    reviews: 150,
    contactNumber: "+91-1234567890",
    availability: "Available",
    images: [
      "https://example.com/images/shutterbugs1.jpg",
      "https://example.com/images/shutterbugs2.jpg",
      "https://example.com/images/shutterbugs3.jpg",
    ],
    customerReviews: [
      { name: "Rohit S.", review: "Amazing shots and very professional!" },
      { name: "Nisha P.", review: "Captured our wedding perfectly." },
    ],
    description:
      "Specializing in wedding photography with a focus on candid moments.",
  },
  {
    id: 2,
    name: "Taste of India Catering",
    location: "MP Nagar",
    serviceType: "Catering",
    priceRange: 35000,
    rating: 5,
    reviews: 200,
    contactNumber: "+91-9876543210",
    availability: "Available",
    images: [
      "https://example.com/images/tasteofindia1.jpg",
      "https://example.com/images/tasteofindia2.jpg",
      "https://example.com/images/tasteofindia3.jpg",
    ],
    customerReviews: [
      { name: "Amit R.", review: "Delicious food and great service!" },
      { name: "Sita M.", review: "Highly recommended for events!" },
    ],
    description: "Providing authentic Indian cuisine for all occasions.",
  },
  {
    id: 3,
    name: "Dream Decorators",
    location: "Lalghati",
    serviceType: "Decoration",
    priceRange: 45000,
    rating: 4,
    reviews: 120,
    contactNumber: "+91-2345678901",
    availability: "Available",
    images: [
      "https://example.com/images/dreamdecorators1.jpg",
      "https://example.com/images/dreamdecorators2.jpg",
      "https://example.com/images/dreamdecorators3.jpg",
    ],
    customerReviews: [
      { name: "Priya K.", review: "Transformed our venue beautifully!" },
      { name: "Raj S.", review: "Attention to detail was impeccable." },
    ],
    description: "Expert in creating stunning decor for weddings and parties.",
  },
  {
    id: 4,
    name: "Euphonic Entertainment",
    location: "Bairagarh",
    serviceType: "Entertainment",
    priceRange: 30000,
    rating: 5,
    reviews: 180,
    contactNumber: "+91-3456789012",
    availability: "Available",
    images: [
      "https://example.com/images/euphonic1.jpg",
      "https://example.com/images/euphonic2.jpg",
      "https://example.com/images/euphonic3.jpg",
    ],
    customerReviews: [
      { name: "Neha T.", review: "Best DJ in town! Had everyone dancing." },
      { name: "Vikram J.", review: "Made our party unforgettable." },
    ],
    description: "Providing top-notch entertainment services for all events.",
  },
  {
    id: 5,
    name: "Elegant Moments Photography",
    location: "Kolar",
    serviceType: "Photography",
    priceRange: 25000,
    rating: 3,
    reviews: 90,
    contactNumber: "+91-4567890123",
    availability: "Unavailable",
    images: [
      "https://example.com/images/elegantmoments1.jpg",
      "https://example.com/images/elegantmoments2.jpg",
      "https://example.com/images/elegantmoments3.jpg",
    ],
    customerReviews: [
      { name: "Samir B.", review: "Good but could improve on timing." },
      { name: "Anjali P.", review: "Photos were decent but not great." },
    ],
    description: "Capturing beautiful moments with an artistic touch.",
  },
  {
    id: 6,
    name: "Royal Treat Catering",
    location: "MP Nagar",
    serviceType: "Catering",
    priceRange: 70000,
    rating: 5,
    reviews: 250,
    contactNumber: "+91-7890123456",
    availability: "Available",
    images: [
      "https://example.com/images/royaltreat1.jpg",
      "https://example.com/images/royaltreat2.jpg",
      "https://example.com/images/royaltreat3.jpg",
    ],
    customerReviews: [
      { name: "Maya S.", review: "Food was exquisite! Will book again." },
      { name: "Karan L.", review: "Outstanding service and variety!" },
    ],
    description: "Specializing in gourmet catering for upscale events.",
  },
  {
    id: 7,
    name: "Starry Nights Decor",
    location: "Lalghati",
    serviceType: "Decoration",
    priceRange: 55000,
    rating: 4,
    reviews: 130,
    contactNumber: "+91-8901234567",
    availability: "Available",
    images: [
      "https://example.com/images/starrynights1.jpg",
      "https://example.com/images/starrynights2.jpg",
      "https://example.com/images/starrynights3.jpg",
    ],
    customerReviews: [
      {
        name: "Asha D.",
        review: "Loved the decorations! Perfect for our theme.",
      },
      { name: "Rahul K.", review: "Very creative and professional." },
    ],
    description: "Creating magical atmospheres for your special occasions.",
  },
  {
    id: 8,
    name: "Fun Fiesta Entertainment",
    location: "Bairagarh",
    serviceType: "Entertainment",
    priceRange: 22000,
    rating: 3,
    reviews: 70,
    contactNumber: "+91-9012345678",
    availability: "Unavailable",
    images: [
      "https://example.com/images/funfiesta1.jpg",
      "https://example.com/images/funfiesta2.jpg",
      "https://example.com/images/funfiesta3.jpg",
    ],
    customerReviews: [
      { name: "Ravi N.", review: "Good entertainment but limited options." },
      { name: "Deepa R.", review: "Fun but could have more activities." },
    ],
    description: "Bringing joy and entertainment to your events.",
  },
  {
    id: 9,
    name: "Epic Wedding Photography",
    location: "Kolar",
    serviceType: "Photography",
    priceRange: 40000,
    rating: 4,
    reviews: 160,
    contactNumber: "+91-2345678901",
    availability: "Available",
    images: [
      "https://example.com/images/epicwedding1.jpg",
      "https://example.com/images/epicwedding2.jpg",
      "https://example.com/images/epicwedding3.jpg",
    ],
    customerReviews: [
      { name: "Anil P.", review: "Incredible work! Loved every shot." },
      { name: "Sneha G.", review: "They captured our day beautifully." },
    ],
    description: "Creating memories through stunning photography.",
  },
  {
    id: 10,
    name: "Flavors of Home Catering",
    location: "MP Nagar",
    serviceType: "Catering",
    priceRange: 25000,
    rating: 4,
    reviews: 90,
    contactNumber: "+91-3214567890",
    availability: "Available",
    images: [
      "https://example.com/images/flavorsofhome1.jpg",
      "https://example.com/images/flavorsofhome2.jpg",
      "https://example.com/images/flavorsofhome3.jpg",
    ],
    customerReviews: [
      { name: "Sunita A.", review: "Home-style food that everyone loved." },
      { name: "Mohit B.", review: "Great taste and presentation." },
    ],
    description: "Bringing the taste of home to your events.",
  },
  {
    id: 11,
    name: "Glamour Decor",
    location: "Lalghati",
    serviceType: "Decoration",
    priceRange: 60000,
    rating: 5,
    reviews: 210,
    contactNumber: "+91-6789012345",
    availability: "Available",
    images: [
      "https://example.com/images/glamourdecor1.jpg",
      "https://example.com/images/glamourdecor2.jpg",
      "https://example.com/images/glamourdecor3.jpg",
    ],
    customerReviews: [
      { name: "Niraj S.", review: "Absolutely stunning setup!" },
      { name: "Vandana M.", review: "Exceeded our expectations." },
    ],
    description: "Elegant decor solutions for every event.",
  },
  {
    id: 12,
    name: "Party Star Entertainment",
    location: "Bairagarh",
    serviceType: "Entertainment",
    priceRange: 18000,
    rating: 3,
    reviews: 50,
    contactNumber: "+91-7654321098",
    availability: "Unavailable",
    images: [
      "https://example.com/images/partystar1.jpg",
      "https://example.com/images/partystar2.jpg",
      "https://example.com/images/partystar3.jpg",
    ],
    customerReviews: [
      { name: "Riya L.", review: "Had fun, but needed more games." },
      { name: "Shyam T.", review: "Entertainment was okay." },
    ],
    description: "Providing a fun experience for parties and events.",
  },
  {
    id: 13,
    name: "Memorable Events Photography",
    location: "Kolar",
    serviceType: "Photography",
    priceRange: 30000,
    rating: 4,
    reviews: 140,
    contactNumber: "+91-6543210987",
    availability: "Available",
    images: [
      "https://example.com/images/memorableevents1.jpg",
      "https://example.com/images/memorableevents2.jpg",
      "https://example.com/images/memorableevents3.jpg",
    ],
    customerReviews: [
      { name: "Ashok R.", review: "Photos turned out great!" },
      { name: "Rita J.", review: "Very professional and friendly." },
    ],
    description: "Capturing every moment with perfection.",
  },
  {
    id: 14,
    name: "Culinary Delights Catering",
    location: "MP Nagar",
    serviceType: "Catering",
    priceRange: 35000,
    rating: 4,
    reviews: 130,
    contactNumber: "+91-5432167890",
    availability: "Available",
    images: [
      "https://example.com/images/culinarydelights1.jpg",
      "https://example.com/images/culinarydelights2.jpg",
      "https://example.com/images/culinarydelights3.jpg",
    ],
    customerReviews: [
      { name: "Kajal M.", review: "Amazing food with great flavors!" },
      { name: "Pradeep N.", review: "Guests raved about the dishes!" },
    ],
    description: "Delicious catering options for any event.",
  },
  {
    id: 15,
    name: "Lavish Decor Co.",
    location: "Lalghati",
    serviceType: "Decoration",
    priceRange: 70000,
    rating: 5,
    reviews: 190,
    contactNumber: "+91-7890654321",
    availability: "Available",
    images: [
      "https://example.com/images/lavishdecor1.jpg",
      "https://example.com/images/lavishdecor2.jpg",
      "https://example.com/images/lavishdecor3.jpg",
    ],
    customerReviews: [
      { name: "Divya P.", review: "Stunning decorations! Highly recommend." },
      { name: "Suresh D.", review: "Made our wedding magical." },
    ],
    description: "Creating opulent settings for every occasion.",
  },
  {
    id: 16,
    name: "Sparkling Events Entertainment",
    location: "Bairagarh",
    serviceType: "Entertainment",
    priceRange: 25000,
    rating: 4,
    reviews: 110,
    contactNumber: "+91-8765432109",
    availability: "Available",
    images: [
      "https://example.com/images/sparklingevents1.jpg",
      "https://example.com/images/sparklingevents2.jpg",
      "https://example.com/images/sparklingevents3.jpg",
    ],
    customerReviews: [
      { name: "Vikas J.", review: "Great entertainment for our party!" },
      { name: "Aditi K.", review: "Kept everyone engaged and entertained." },
    ],
    description: "Providing lively entertainment for events and parties.",
  },
  {
    id: 17,
    name: "Epicurean Catering",
    location: "Kolar",
    serviceType: "Catering",
    priceRange: 40000,
    rating: 5,
    reviews: 200,
    contactNumber: "+91-5432109876",
    availability: "Available",
    images: [
      "https://example.com/images/epicurean1.jpg",
      "https://example.com/images/epicurean2.jpg",
      "https://example.com/images/epicurean3.jpg",
    ],
    customerReviews: [
      { name: "Sophie T.", review: "Food was gourmet and amazing!" },
      { name: "Aditya P.", review: "A culinary experience to remember!" },
    ],
    description: "Gourmet catering for special occasions.",
  },
  {
    id: 18,
    name: "Radiant Photography",
    location: "MP Nagar",
    serviceType: "Photography",
    priceRange: 23000,
    rating: 4,
    reviews: 150,
    contactNumber: "+91-6549873210",
    availability: "Available",
    images: [
      "https://example.com/images/radiantphotography1.jpg",
      "https://example.com/images/radiantphotography2.jpg",
      "https://example.com/images/radiantphotography3.jpg",
    ],
    customerReviews: [
      { name: "Tanya R.", review: "Stunning photos and great service." },
      {
        name: "Nikhil J.",
        review: "Captured our special moments beautifully.",
      },
    ],
    description: "Providing high-quality photography services.",
  },
  {
    id: 19,
    name: "Majestic Events Decor",
    location: "Lalghati",
    serviceType: "Decoration",
    priceRange: 50000,
    rating: 5,
    reviews: 180,
    contactNumber: "+91-3214569870",
    availability: "Available",
    images: [
      "https://example.com/images/majesticdecor1.jpg",
      "https://example.com/images/majesticdecor2.jpg",
      "https://example.com/images/majesticdecor3.jpg",
    ],
    customerReviews: [
      { name: "Anushka G.", review: "Absolutely loved the decor!" },
      { name: "Rajesh H.", review: "Made our venue look spectacular." },
    ],
    description: "Transforming venues with stunning decor.",
  },
  {
    id: 20,
    name: "Karaoke Party Entertainment",
    location: "Bairagarh",
    serviceType: "Entertainment",
    priceRange: 12000,
    rating: 3,
    reviews: 60,
    contactNumber: "+91-8765432109",
    availability: "Unavailable",
    images: [
      "https://example.com/images/karaokeparty1.jpg",
      "https://example.com/images/karaokeparty2.jpg",
      "https://example.com/images/karaokeparty3.jpg",
    ],
    customerReviews: [
      { name: "Rohan K.", review: "Fun experience for our group!" },
      {
        name: "Simran P.",
        review: "Good selection of songs but limited equipment.",
      },
    ],
    description: "Bringing karaoke fun to your events.",
  },
  {
    id: 21,
    name: "Candid Captures Photography",
    location: "Kolar",
    serviceType: "Photography",
    priceRange: 32000,
    rating: 4,
    reviews: 130,
    contactNumber: "+91-5432156780",
    availability: "Available",
    images: [
      "https://example.com/images/candidcaptures1.jpg",
      "https://example.com/images/candidcaptures2.jpg",
      "https://example.com/images/candidcaptures3.jpg",
    ],
    customerReviews: [
      { name: "Kavita M.", review: "Captured beautiful moments!" },
      { name: "Amit P.", review: "Very satisfied with the service." },
    ],
    description: "Specializing in candid photography for weddings and events.",
  },
  {
    id: 22,
    name: "Epicurean Events Catering",
    location: "MP Nagar",
    serviceType: "Catering",
    priceRange: 28000,
    rating: 5,
    reviews: 160,
    contactNumber: "+91-6543217890",
    availability: "Available",
    images: [
      "https://example.com/images/epicureanevents1.jpg",
      "https://example.com/images/epicureanevents2.jpg",
      "https://example.com/images/epicureanevents3.jpg",
    ],
    customerReviews: [
      { name: "Nishant K.", review: "Wonderful food, everyone loved it!" },
      { name: "Tania J.", review: "Exceptional service and quality." },
    ],
    description: "Catering services that delight your palate.",
  },
  {
    id: 23,
    name: "Starlit Decorators",
    location: "Lalghati",
    serviceType: "Decoration",
    priceRange: 48000,
    rating: 5,
    reviews: 210,
    contactNumber: "+91-7654321090",
    availability: "Available",
    images: [
      "https://example.com/images/starlitdecor1.jpg",
      "https://example.com/images/starlitdecor2.jpg",
      "https://example.com/images/starlitdecor3.jpg",
    ],
    customerReviews: [
      { name: "Divya S.", review: "Incredible decor for our wedding!" },
      { name: "Karan B.", review: "Exceeded our expectations." },
    ],
    description: "Providing exquisite decor for all events.",
  },
  {
    id: 24,
    name: "Dreams Come True Catering",
    location: "Bairagarh",
    serviceType: "Catering",
    priceRange: 32000,
    rating: 4,
    reviews: 190,
    contactNumber: "+91-9876543210",
    availability: "Available",
    images: [
      "https://example.com/images/dreamscometrue1.jpg",
      "https://example.com/images/dreamscometrue2.jpg",
      "https://example.com/images/dreamscometrue3.jpg",
    ],
    customerReviews: [
      { name: "Manish G.", review: "Great variety of dishes!" },
      { name: "Sanjay R.", review: "Food was delicious and well-presented." },
    ],
    description: "Creating delicious memories for every occasion.",
  },
  {
    id: 25,
    name: "Whimsical Events Entertainment",
    location: "Kolar",
    serviceType: "Entertainment",
    priceRange: 26000,
    rating: 4,
    reviews: 120,
    contactNumber: "+91-6543210987",
    availability: "Available",
    images: [
      "https://example.com/images/whimsicalevents1.jpg",
      "https://example.com/images/whimsicalevents2.jpg",
      "https://example.com/images/whimsicalevents3.jpg",
    ],
    customerReviews: [
      { name: "Meera D.", review: "Fun and engaging for everyone!" },
      { name: "Rahul K.", review: "Great variety of entertainment options." },
    ],
    description: "Bringing whimsical fun to your events.",
  },
  {
    id: 26,
    name: "Gourmet Delights Catering",
    location: "MP Nagar",
    serviceType: "Catering",
    priceRange: 55000,
    rating: 5,
    reviews: 170,
    contactNumber: "+91-8765432109",
    availability: "Available",
    images: [
      "https://example.com/images/gourmetdelights1.jpg",
      "https://example.com/images/gourmetdelights2.jpg",
      "https://example.com/images/gourmetdelights3.jpg",
    ],
    customerReviews: [
      { name: "Rashmi S.", review: "Exquisite taste and presentation." },
      { name: "Vikram T.", review: "Our guests were impressed!" },
    ],
    description: "Luxury catering for special events.",
  },
  {
    id: 27,
    name: "Event Bliss Photography",
    location: "Lalghati",
    serviceType: "Photography",
    priceRange: 18000,
    rating: 3,
    reviews: 75,
    contactNumber: "+91-3216549870",
    availability: "Unavailable",
    images: [
      "https://example.com/images/eventbliss1.jpg",
      "https://example.com/images/eventbliss2.jpg",
      "https://example.com/images/eventbliss3.jpg",
    ],
    customerReviews: [
      { name: "Priya A.", review: "Photos were decent, but not great." },
      { name: "Gaurav B.", review: "They missed some key moments." },
    ],
    description: "Delivering decent photography for events.",
  },
  {
    id: 28,
    name: "Dazzling Decor Co.",
    location: "Bairagarh",
    serviceType: "Decoration",
    priceRange: 42000,
    rating: 5,
    reviews: 200,
    contactNumber: "+91-5432167890",
    availability: "Available",
    images: [
      "https://example.com/images/dazzlingdecor1.jpg",
      "https://example.com/images/dazzlingdecor2.jpg",
      "https://example.com/images/dazzlingdecor3.jpg",
    ],
    customerReviews: [
      { name: "Ritika L.", review: "Stunning decor for our party!" },
      { name: "Ajay P.", review: "Made everything look beautiful." },
    ],
    description: "Creating dazzling settings for your events.",
  },
  {
    id: 29,
    name: "Grand Celebrations Entertainment",
    location: "Kolar",
    serviceType: "Entertainment",
    priceRange: 21000,
    rating: 3,
    reviews: 50,
    contactNumber: "+91-3219876540",
    availability: "Available",
    images: [
      "https://example.com/images/grandcelebrations1.jpg",
      "https://example.com/images/grandcelebrations2.jpg",
      "https://example.com/images/grandcelebrations3.jpg",
    ],
    customerReviews: [
      { name: "Neha M.", review: "It was fun but could be better." },
      { name: "Sahil K.", review: "Good energy, but missing some activities." },
    ],
    description: "Adding joy and excitement to celebrations.",
  },
  {
    id: 30,
    name: "Elegant Moments Photography",
    location: "MP Nagar",
    serviceType: "Photography",
    priceRange: 27000,
    rating: 5,
    reviews: 220,
    contactNumber: "+91-5432198760",
    availability: "Available",
    images: [
      "https://example.com/images/elegantmoments1.jpg",
      "https://example.com/images/elegantmoments2.jpg",
      "https://example.com/images/elegantmoments3.jpg",
    ],
    customerReviews: [
      { name: "Kriti S.", review: "Captivating moments beautifully captured!" },
      { name: "Ravi G.", review: "Professional and artistic work." },
    ],
    description: "Specializing in capturing elegant moments.",
  },
];

export default VendorData;
