const VenueData = [
  {
    id: 1,
    name: "Woodapple Residency",
    location: "Bairagarh",
    address:
      "3, Hargobind Enclave, Vikas Marg, Opp. Metro Pillar 114, New Delhi 110092",
    views: 35207,
    guestCapacity: "50 - 150 Guests",
    rating: 4.5,
    reviews: 80,
    vegPrice: 445,
    nonVegPrice: "₹1199 / Pax",
    rooms: 18,
    availability: "Available",
    alcoholServed: "Yes",
    images: [
      "https://cdn.venuelook.com/uploads/space_39596/1724497691_595x400.png",
      "https://cdn.venuelook.com/uploads/space_39596/1724497706_595x400.png",
      "https://cdn.venuelook.com/uploads/space_39596/1724497709_595x400.png",
    ],
    contactNumber: "+91-7669496932",
    amenities: ["WiFi", "AC", "Projector", "Parking"],
    customerReviews: [
      { name: "Anita S.", review: "Great place for events! Highly recommend." },
      {
        name: "Rahul K.",
        review: "Food was amazing and service was excellent.",
      },
    ],
    description:
      "A spacious and well-decorated venue ideal for weddings and corporate events.",
    type: "Veg & NonVeg Both",
    occasion: "Family Get Together",
    budget: "Under 400",
  },
  {
    id: 2,
    name: "Royal Banquet Hall",
    location: "Kolar",
    address: "12, Kolar Road, Bhopal, Madhya Pradesh 462042",
    views: 21405,
    guestCapacity: "100 - 300 Guests",
    rating: 4.2,
    reviews: 50,
    vegPrice: 700,
    nonVegPrice: "₹1000 / Pax",
    rooms: 20,
    availability: "Available",
    alcoholServed: "No",
    images: [
      "https://imgs.search.brave.com/gjUuvIBRiKIGUkqBiJpPy3QOehmpDdjus_WvDOumnb0/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly93d3cu/amF5cGVlaG90ZWxz/LmNvbS9pbWFnZXMv/d2VkZGluZy1wYWdl/L291ciUyMHZlbnVz/JTIwLTUuanBn",
    ],
    contactNumber: "+91-9123456789",
    amenities: ["Parking", "Catering", "Decor", "Sound System"],
    customerReviews: [
      { name: "Suresh M.", review: "Nice venue with good facilities." },
      { name: "Neha R.", review: "Had my wedding here; it was perfect!" },
    ],
    description:
      "An elegant banquet hall suitable for large gatherings and celebrations.",
    type: "Pure Veg",
    occasion: "Wedding",
    budget: "601 to 800",
  },
  {
    id: 3,
    name: "Elegant Events Center",
    location: "MP Nagar",
    address: "45, MP Nagar, Zone II, Bhopal, Madhya Pradesh 462011",
    views: 18425,
    guestCapacity: "30 - 80 Guests",
    rating: 4.7,
    reviews: 30,
    vegPrice: 850,
    nonVegPrice: "₹1100 / Pax",
    rooms: 5,
    availability: "Available",
    alcoholServed: "Yes",
    images: [
      "https://imgs.search.brave.com/ItY38j4OwSq4xBa7G-F2MDWmDuEr23-kPaBF8iyZBP8/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXdlZHoub3lvcm9v/bXNjZG4uY29tL21l/ZGl1bS9waG90b2xv/Z3VlL2ltYWdlcy9y/YWFqa3V0aXItc3dh/Ymh1bWktc2FsdGxh/a2UtY2l0eS1rb2xr/YXRhLmpwZw",
    ],
    contactNumber: "+91-9876543210",
    amenities: ["WiFi", "Projector", "Catering", "Parking"],
    customerReviews: [
      { name: "Meera P.", review: "Very accommodating and friendly staff." },
      { name: "Raj T.", review: "A perfect place for small parties!" },
    ],
    description: "A cozy venue with modern amenities for intimate gatherings.",
    type: "Veg & NonVeg Both",
    occasion: "Birthday Party",
    budget: "401 to 600",
  },
  {
    id: 4,
    name: "Celebration Hall",
    location: "Lalghati",
    address: "67, Lalghati Road, Bhopal, Madhya Pradesh 462036",
    views: 12500,
    guestCapacity: "200 - 400 Guests",
    rating: 4.0,
    reviews: 70,
    vegPrice: 900,
    nonVegPrice: "₹1300 / Pax",
    rooms: 15,
    availability: "Available",
    alcoholServed: "Yes",
    images: [
      "https://imgs.search.brave.com/ohuEQ7HbGOF9hmoAKruJc_i-WlAdTuvFOmyo5BoBi2A/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9hcG9s/bG8ub2x4LmluL3Yx/L2ZpbGVzL2tnMmRj/NDcweTlwcDItSU4v/aW1hZ2U7cz0yNzJ4/MA.jpeg",
    ],
    contactNumber: "+91-7654321098",
    amenities: ["Catering", "Decor", "WiFi", "Air Conditioning"],
    customerReviews: [
      { name: "Kiran J.", review: "Spacious and beautifully decorated." },
      { name: "Vikram S.", review: "Great for large weddings!" },
    ],
    description:
      "A large hall perfect for weddings, receptions, and grand events.",
    type: "Pure Veg",
    occasion: "wedding",
    budget: "801 to 1000",
  },
  {
    id: 5,
    name: "Paradise Party Place",
    location: "Minal",
    address: "89, Minal Residency, Bhopal, Madhya Pradesh 462023",
    views: 30000,
    guestCapacity: "150 - 250 Guests",
    rating: 4.3,
    reviews: 65,
    vegPrice: 750,
    nonVegPrice: "₹1150 / Pax",
    rooms: 10,
    availability: "Available",
    alcoholServed: "No",
    images: [
      "https://imgs.search.brave.com/LBn963GZF2MRSIqM1W0SHpgQ0Jg29VGdfo5lC6jJbZU/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9jb250/ZW50LmpkbWFnaWNi/b3guY29tL2NvbXAv/bXVtYmFpL3Q5LzAy/MnB4eDIyLnh4MjIu/MjExMjAzMTQxMTEy/LnAzdDkvY2F0YWxv/Z3VlL2JhbGFqaS1i/YW5xdWV0LWhhbGwt/cGFudmVsLW11bWJh/aS1iYW5xdWV0LWhh/bGxzLXoyazl3ZWlz/ZTIuanBn",
    ],
    contactNumber: "+91-9432156789",
    amenities: ["Parking", "Sound System", "Lighting", "Catering"],
    customerReviews: [
      { name: "Sonia L.", review: "Amazing atmosphere and service." },
      {
        name: "Gaurav D.",
        review: "Had a wonderful family get-together here.",
      },
    ],
    description: "A vibrant venue for celebrations, parties, and gatherings.",
    type: "Veg & NonVeg Both",
    occasion: "Family Get Together",
    budget: "Under 400",
  },
  {
    id: 6,
    name: "The Grand Pavilion",
    location: "Kolar",
    address: "123, Kolar, Bhopal, Madhya Pradesh 462047",
    views: 5000,
    guestCapacity: "300 - 500 Guests",
    rating: 4.9,
    reviews: 100,
    vegPrice: 1200,
    nonVegPrice: "₹1500 / Pax",
    rooms: 30,
    availability: "Available",
    alcoholServed: "Yes",
    images: [
      "https://imgs.search.brave.com/dxPMB9fpeoQpATDZNfALAYt1dZqgFcD_n_zBhKhOP04/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9hcG9s/bG8ub2x4LmluL3Yx/L2ZpbGVzL2ZoMjEx/cXVhdHlwazEtSU4v/aW1hZ2U7cz0yNzJ4/MA.jpeg",
    ],
    contactNumber: "+91-9191919191",
    amenities: ["WiFi", "Catering", "Decor", "Projector"],
    customerReviews: [
      { name: "Kavita S.", review: "The best venue for grand events!" },
      { name: "Anil K.", review: "Everything was just perfect!" },
    ],
    description: "An extravagant venue for luxurious celebrations and events.",
    type: "Pure Veg",
    occasion: "Wedding",
    budget: "1001 to 1200",
  },
  {
    id: 7,
    name: "Charming Celebrations",
    location: "Minal",
    address: "45, Minal Road, Bhopal, Madhya Pradesh 462025",
    views: 22000,
    guestCapacity: "80 - 200 Guests",
    rating: 4.4,
    reviews: 45,
    vegPrice: 950,
    nonVegPrice: "₹1300 / Pax",
    rooms: 12,
    availability: "Available",
    alcoholServed: "No",
    images: [
      "https://imgs.search.brave.com/LvCeej9oQZkaQulqwnPX3GyDXsSW9j519QUR90d0K_k/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzL2I2LzFi/Lzg0L2I2MWI4NDM3/MWZmNWRlY2I0YjE5/N2M3YWI5OGEwYzE2/LmpwZw",
    ],
    contactNumber: "+91-8765432109",
    amenities: ["WiFi", "Parking", "AC"],
    customerReviews: [
      { name: "Nina R.", review: "Lovely venue with great ambiance." },
      { name: "Rajesh T.", review: "Had my engagement here; it was a dream!" },
    ],
    description: "A charming venue for smaller gatherings and celebrations.",
    type: "Veg & NonVeg Both",
    occasion: "Engagement",
    budget: "401 to 600",
  },
  {
    id: 8,
    name: "The Vintage Mansion",
    location: "Lalghati",
    address: "67, Lalghati Road, Bhopal, Madhya Pradesh 462036",
    views: 15000,
    guestCapacity: "100 - 250 Guests",
    rating: 4.6,
    reviews: 90,
    vegPrice: 1100,
    nonVegPrice: "₹1450 / Pax",
    rooms: 8,
    availability: "Available",
    alcoholServed: "Yes",
    images: [
      "https://imgs.search.brave.com/mZ65uZ3KYq10imcXOKzWKqyPmJ6qtS-4CUsSEQsegwc/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9jZG4w/LndlZGRpbmd3aXJl/LmluL3ZlbmRvci85/NDUyLzNfMi82NDAv/anBnL2JhbnF1ZXQt/aW1nMS5qcGVn",
    ],
    contactNumber: "+91-7894561230",
    amenities: ["Catering", "Parking", "Decor"],
    customerReviews: [
      {
        name: "Alok M.",
        review: "An exquisite venue with a beautiful setting.",
      },
      { name: "Shruti S.", review: "Perfect for family gatherings." },
    ],
    description:
      "A vintage venue offering a unique charm for special occasions.",
    type: "Pure Veg",
    occasion: "Family Get Together",
    budget: "801 to 1000",
  },
  {
    id: 9,
    name: "Sky High Rooftop",
    location: "Kolar",
    address: "58, Kolar, Bhopal, Madhya Pradesh 462048",
    views: 27000,
    guestCapacity: "20 - 60 Guests",
    rating: 4.8,
    reviews: 30,
    vegPrice: 850,
    nonVegPrice: "₹1150 / Pax",
    rooms: 5,
    availability: "Available",
    alcoholServed: "Yes",
    images: [
      "https://imgs.search.brave.com/y5tdlFB9-HeD_fhgBMRTc_YFbtRzMpBEOEahx0fcA64/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzQwLzIw/LzliLzQwMjA5YjAx/YzQ5ZGNjMTY1NmIy/NzA4NjFhMmIwNTA2/LmpwZw",
    ],
    contactNumber: "+91-9999999999",
    amenities: ["WiFi", "Lighting", "Catering"],
    customerReviews: [
      { name: "Meena L.", review: "The view is to die for!" },
      { name: "Rohit K.", review: "Great place for intimate parties." },
    ],
    description:
      "A rooftop venue with stunning views, perfect for small celebrations.",
    type: "Veg & NonVeg Both",
    occasion: "Birthday Party",
    budget: "Under 400",
  },
  {
    id: 10,
    name: "Serene Gardens",
    location: "Minal",
    address: "36, Minal Residency, Bhopal, Madhya Pradesh 462024",
    views: 9000,
    guestCapacity: "100 - 300 Guests",
    rating: 4.1,
    reviews: 40,
    vegPrice: 700,
    nonVegPrice: "₹1000 / Pax",
    rooms: 0,
    availability: "Available",
    alcoholServed: "No",
    images: [
      "https://cdn.venuelook.com/uploads/space_39596/1724497691_595x400.png",
    ],
    contactNumber: "+91-7531598462",
    amenities: ["WiFi", "Catering", "Parking"],
    customerReviews: [
      { name: "Anu P.", review: "A beautiful garden setting for weddings." },
      { name: "Suresh K.", review: "Peaceful and lovely ambiance." },
    ],
    description: "A serene garden venue perfect for outdoor events.",
    type: "Pure Veg",
    occasion: "Wedding",
    budget: "601 to 800",
  },
  {
    id: 11,
    name: "Majestic Hall",
    location: "Bairagarh",
    address: "2, Hargobind Enclave, Bhopal, Madhya Pradesh 462020",
    views: 11000,
    guestCapacity: "50 - 150 Guests",
    rating: 4.3,
    reviews: 55,
    vegPrice: 950,
    nonVegPrice: "₹1350 / Pax",
    rooms: 10,
    availability: "Available",
    alcoholServed: "Yes",
    images: [
      "https://cdn.venuelook.com/uploads/space_39596/1724497691_595x400.png",
    ],
    contactNumber: "+91-7531598463",
    amenities: ["WiFi", "Projector", "Catering"],
    customerReviews: [
      { name: "Priya T.", review: "Great place for corporate events!" },
      {
        name: "Rajesh K.",
        review: "Food was delicious and service was excellent.",
      },
    ],
    description: "A majestic hall for corporate events, weddings, and parties.",
    type: "Veg & NonVeg Both",
    occasion: "Corporate Event",
    budget: "1001 to 1200",
  },
  {
    id: 12,
    name: "The Orchid Lounge",
    location: "MP Nagar",
    address: "25, MP Nagar, Bhopal, Madhya Pradesh 462019",
    views: 13000,
    guestCapacity: "80 - 200 Guests",
    rating: 4.5,
    reviews: 50,
    vegPrice: 850,
    nonVegPrice: "₹1200 / Pax",
    rooms: 12,
    availability: "Available",
    alcoholServed: "Yes",
    images: [
      "https://cdn.venuelook.com/uploads/space_39596/1724497691_595x400.png",
    ],
    contactNumber: "+91-7531598464",
    amenities: ["WiFi", "Catering", "Parking"],
    customerReviews: [
      { name: "Nisha R.", review: "Perfect for cocktail parties!" },
      { name: "Deepak P.", review: "Stylish and classy venue." },
    ],
    description: "An elegant lounge for sophisticated events and gatherings.",
    type: "Veg & NonVeg Both",
    occasion: "Cocktail Party",
    budget: "601 to 800",
  },
  {
    id: 13,
    name: "Sunset Beach Resort",
    location: "Lalghati",
    address: "89, Sunset Road, Bhopal, Madhya Pradesh 462037",
    views: 27000,
    guestCapacity: "150 - 400 Guests",
    rating: 4.6,
    reviews: 65,
    vegPrice: 1200,
    nonVegPrice: "₹1600 / Pax",
    rooms: 25,
    availability: "Available",
    alcoholServed: "Yes",
    images: [
      "https://cdn.venuelook.com/uploads/space_39596/1724497691_595x400.png",
    ],
    contactNumber: "+91-7531598465",
    amenities: ["WiFi", "Catering", "Beach Access"],
    customerReviews: [
      {
        name: "Poonam S.",
        review: "A beautiful resort for destination weddings.",
      },
      { name: "Arjun M.", review: "Great beach view and hospitality." },
    ],
    description: "A beachside resort ideal for wedding and vacation events.",
    type: "Veg & NonVeg Both",
    occasion: "Destination Wedding",
    budget: "1001 to 1200",
  },
  {
    id: 14,
    name: "Elysium Event Hall",
    location: "Kolar",
    address: "55, Kolar Road, Bhopal, Madhya Pradesh 462050",
    views: 19000,
    guestCapacity: "50 - 100 Guests",
    rating: 4.4,
    reviews: 40,
    vegPrice: 900,
    nonVegPrice: "₹1350 / Pax",
    rooms: 8,
    availability: "Available",
    alcoholServed: "No",
    images: [
      "https://cdn.venuelook.com/uploads/space_39596/1724497691_595x400.png",
    ],
    contactNumber: "+91-7531598466",
    amenities: ["WiFi", "Catering", "Lighting"],
    customerReviews: [
      { name: "Alok S.", review: "Perfect for intimate gatherings." },
      { name: "Priyanka G.", review: "Loved the decor and ambiance!" },
    ],
    description: "An elegant hall for smaller events with a cozy atmosphere.",
    type: "Pure Veg",
    occasion: "Family Get Together",
    budget: "601 to 800",
  },
  {
    id: 15,
    name: "Green Valley Banquet",
    location: "Minal",
    address: "67, Green Valley Road, Bhopal, Madhya Pradesh 462051",
    views: 24000,
    guestCapacity: "100 - 250 Guests",
    rating: 4.7,
    reviews: 55,
    vegPrice: 1100,
    nonVegPrice: "₹1500 / Pax",
    rooms: 20,
    availability: "Available",
    alcoholServed: "Yes",
    images: [
      "https://cdn.venuelook.com/uploads/space_39596/1724497691_595x400.png",
    ],
    contactNumber: "+91-7531598467",
    amenities: ["WiFi", "Parking", "Catering"],
    customerReviews: [
      { name: "Sandeep M.", review: "Great for weddings and parties!" },
      { name: "Rita A.", review: "Amazing service and food!" },
    ],
    description:
      "A banquet hall surrounded by lush greenery, perfect for grand events.",
    type: "Veg & NonVeg Both",
    occasion: "Wedding",
    budget: "801 to 1000",
  },
  {
    id: 16,
    name: "Crystal Palace",
    location: "Bairagarh",
    address: "42, Crystal Palace Road, Bhopal, Madhya Pradesh 462022",
    views: 30000,
    guestCapacity: "80 - 200 Guests",
    rating: 4.2,
    reviews: 60,
    vegPrice: 950,
    nonVegPrice: "₹1350 / Pax",
    rooms: 15,
    availability: "Available",
    alcoholServed: "Yes",
    images: [
      "https://cdn.venuelook.com/uploads/space_39596/1724497691_595x400.png",
    ],
    contactNumber: "+91-7531598468",
    amenities: ["WiFi", "Catering", "Lighting"],
    customerReviews: [
      { name: "Shalini D.", review: "Lovely venue with great food!" },
      { name: "Rajesh R.", review: "The decor was stunning!" },
    ],
    description: "A beautiful palace venue ideal for luxurious events.",
    type: "Veg & NonVeg Both",
    occasion: "Corporate Event",
    budget: "1001 to 1200",
  },
  {
    id: 17,
    name: "Eden Resort",
    location: "Kolar",
    address: "75, Eden Road, Bhopal, Madhya Pradesh 462052",
    views: 20000,
    guestCapacity: "150 - 300 Guests",
    rating: 4.5,
    reviews: 70,
    vegPrice: 1150,
    nonVegPrice: "₹1600 / Pax",
    rooms: 30,
    availability: "Available",
    alcoholServed: "Yes",
    images: [
      "https://cdn.venuelook.com/uploads/space_39596/1724497691_595x400.png",
    ],
    contactNumber: "+91-7531598469",
    amenities: ["WiFi", "Catering", "Parking"],
    customerReviews: [
      { name: "Gauri T.", review: "An incredible place for weddings!" },
      { name: "Karan M.", review: "Beautiful venue with excellent service." },
    ],
    description:
      "A resort venue with beautiful gardens and top-notch amenities.",
    type: "Veg & NonVeg Both",
    occasion: "Wedding",
    budget: "1001 to 1200",
  },
  {
    id: 18,
    name: "Riverfront Pavilion",
    location: "Mandideep",
    address: "15, Riverfront Road, Mandideep, Madhya Pradesh 462046",
    views: 18000,
    guestCapacity: "100 - 250 Guests",
    rating: 4.4,
    reviews: 45,
    vegPrice: 900,
    nonVegPrice: "₹1300 / Pax",
    rooms: 0,
    availability: "Available",
    alcoholServed: "No",
    images: [
      "https://cdn.venuelook.com/uploads/space_39596/1724497691_595x400.png",
    ],
    contactNumber: "+91-7531598470",
    amenities: ["Catering", "Parking", "Scenic View"],
    customerReviews: [
      { name: "Maya R.", review: "A great place for outdoor events!" },
      { name: "Ajay K.", review: "Scenic views and great food." },
    ],
    description:
      "A scenic venue located by the river, ideal for outdoor events.",
    type: "Pure Veg",
    occasion: "Outdoor Event",
    budget: "601 to 800",
  },
  {
    id: 19,
    name: "Hillside Retreat",
    location: "Hoshangabad",
    address: "9, Hillside Road, Hoshangabad, Madhya Pradesh 461001",
    views: 17000,
    guestCapacity: "200 - 500 Guests",
    rating: 4.7,
    reviews: 75,
    vegPrice: 1300,
    nonVegPrice: "₹1800 / Pax",
    rooms: 50,
    availability: "Available",
    alcoholServed: "Yes",
    images: [
      "https://cdn.venuelook.com/uploads/space_39596/1724497691_595x400.png",
    ],
    contactNumber: "+91-7531598471",
    amenities: ["WiFi", "Catering", "Parking"],
    customerReviews: [
      { name: "Ravi G.", review: "An amazing venue for big celebrations!" },
      { name: "Simran T.", review: "Stunning views and great service." },
    ],
    description:
      "A hillside retreat offering breathtaking views for large gatherings.",
    type: "Veg & NonVeg Both",
    occasion: "Large Event",
    budget: "1201 to 1500",
  },
  {
    id: 20,
    name: "Urban Lounge",
    location: "Hoshangabad",
    address: "10, Urban Road, Hoshangabad, Madhya Pradesh 461002",
    views: 16000,
    guestCapacity: "40 - 100 Guests",
    rating: 4.3,
    reviews: 30,
    vegPrice: 800,
    nonVegPrice: "₹1200 / Pax",
    rooms: 5,
    availability: "Available",
    alcoholServed: "Yes",
    images: [
      "https://cdn.venuelook.com/uploads/space_39596/1724497691_595x400.png",
    ],
    contactNumber: "+91-7531598472",
    amenities: ["WiFi", "Catering", "Lighting"],
    customerReviews: [
      { name: "Nitin J.", review: "Perfect for small gatherings." },
      { name: "Kavita S.", review: "Chic and modern atmosphere." },
    ],
    description: "A trendy lounge venue for private events and gatherings.",
    type: "Veg & NonVeg Both",
    occasion: "Private Party",
    budget: "Under 400",
  },
  {
    id: 21,
    name: "Crystal Palace",
    location: "Bhopal",
    address: "21, Crystal Road, Madhya Pradesh 462001",
    views: 30000,
    guestCapacity: "80 - 200 Guests",
    rating: 4.2,
    reviews: 60,
    vegPrice: 950,
    nonVegPrice: "₹1350 / Pax",
    rooms: 15,
    availability: "Available",
    alcoholServed: "Yes",
    images: [
      "https://cdn.venuelook.com/uploads/space_39596/1724497691_595x400.png",
    ],
    contactNumber: "+91-7531598473",
    amenities: ["WiFi", "Catering", "Lighting"],
    customerReviews: [
      { name: "Shalini D.", review: "Lovely venue with great food!" },
      { name: "Rajesh R.", review: "The decor was stunning!" },
    ],
    description: "A beautiful palace venue ideal for luxurious events.",
    type: "Veg & NonVeg Both",
    occasion: "Corporate Event",
    budget: "1001 to 1200",
  },
  {
    id: 22,
    name: "Eden Resort",
    location: "Kolar",
    address: "75, Eden Road, Madhya Pradesh 462052",
    views: 20000,
    guestCapacity: "150 - 300 Guests",
    rating: 4.5,
    reviews: 70,
    vegPrice: 1150,
    nonVegPrice: "₹1600 / Pax",
    rooms: 30,
    availability: "Available",
    alcoholServed: "Yes",
    images: [
      "https://cdn.venuelook.com/uploads/space_39596/1724497691_595x400.png",
    ],
    contactNumber: "+91-7531598474",
    amenities: ["WiFi", "Catering", "Parking"],
    customerReviews: [
      { name: "Gauri T.", review: "An incredible place for weddings!" },
      { name: "Karan M.", review: "Beautiful venue with excellent service." },
    ],
    description:
      "A resort venue with beautiful gardens and top-notch amenities.",
    type: "Veg & NonVeg Both",
    occasion: "Wedding",
    budget: "1001 to 1200",
  },
  {
    id: 23,
    name: "Riverfront Pavilion",
    location: "Mandideep",
    address: "15, Riverfront Road, Mandideep, Madhya Pradesh 462046",
    views: 18000,
    guestCapacity: "100 - 250 Guests",
    rating: 4.4,
    reviews: 45,
    vegPrice: 900,
    nonVegPrice: "1300 / Pax",
    rooms: 0,
    availability: "Available",
    alcoholServed: "No",
    images: [
      "https://cdn.venuelook.com/uploads/space_39596/1724497691_595x400.png",
    ],
    contactNumber: "+91-7531598475",
    amenities: ["Catering", "Parking", "Scenic View"],
    customerReviews: [
      { name: "Maya R.", review: "A great place for outdoor events!" },
      { name: "Ajay K.", review: "Scenic views and great food." },
    ],
    description:
      "A scenic venue located by the river, ideal for outdoor events.",
    type: "Pure Veg",
    occasion: "Outdoor Event",
    budget: "601 to 800",
  },
  {
    id: 24,
    name: "Hillside Retreat",
    location: "Hoshangabad",
    address: "9, Hillside Road, Hoshangabad, Madhya Pradesh 461001",
    views: 17000,
    guestCapacity: "200 - 500 Guests",
    rating: 4.7,
    reviews: 75,
    vegPrice: 1300,
    nonVegPrice: "₹1800 / Pax",
    rooms: 50,
    availability: "Available",
    alcoholServed: "Yes",
    images: [
      "https://cdn.venuelook.com/uploads/space_39596/1724497691_595x400.png",
    ],
    contactNumber: "+91-7531598476",
    amenities: ["WiFi", "Catering", "Parking"],
    customerReviews: [
      { name: "Ravi G.", review: "An amazing venue for big celebrations!" },
      { name: "Simran T.", review: "Stunning views and great service." },
    ],
    description:
      "A hillside retreat offering breathtaking views for large gatherings.",
    type: "Veg & NonVeg Both",
    occasion: "Large Event",
    budget: "1201 to 1500",
  },
  {
    id: 25,
    name: "Urban Lounge",
    location: "Hoshangabad",
    address: "10, Urban Road, Hoshangabad, Madhya Pradesh 461002",
    views: 16000,
    guestCapacity: "40 - 100 Guests",
    rating: 4.3,
    reviews: 30,
    vegPrice: 800,
    nonVegPrice: "₹1200 / Pax",
    rooms: 5,
    availability: "Available",
    alcoholServed: "Yes",
    images: [
      "https://cdn.venuelook.com/uploads/space_39596/1724497691_595x400.png",
    ],
    contactNumber: "+91-7531598477",
    amenities: ["WiFi", "Catering", "Lighting"],
    customerReviews: [
      { name: "Nitin J.", review: "Perfect for small gatherings." },
      { name: "Kavita S.", review: "Chic and modern atmosphere." },
    ],
    description: "A trendy lounge venue for private events and gatherings.",
    type: "Veg & NonVeg Both",
    occasion: "Private Party",
    budget: "Under 400",
  },
];

export default VenueData;
